# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

service: trianglify-lambda

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${env:S3_BUCKET}/*"

plugins:
  - serverless-dotenv-plugin # allows local usage using a .env file

functions:
  trianglify:
    handler: handler.trianglify
